# Generated by Django 5.2.4 on 2025-08-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
