# Generated by Django 5.2.4 on 2025-08-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0002_remove_pizza_quantity_remove_pizza_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
