# Generated by Django 5.2.4 on 2025-08-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0003_alter_pizza_description_alter_pizza_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='price',
            new_name='large_price',
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=10),
        ),
        migrations.AddField(
            model_name='pizza',
            name='medium_price',
            field=models.DecimalField(decimal_places=2, default=12.99, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='small_price',
            field=models.DecimalField(decimal_places=2, default=15.99, max_digits=6),
            preserve_default=False,
        ),
    ]
